name: React Vite PR Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Clean node_modules and lockfile
        run: |
          rm -rf node_modules package-lock.json

      - name: Install dependencies with legacy peer deps
        run: |
          npm install --legacy-peer-deps
          npm install rollup@latest --build-from-source

      - name: Build project
        run: npm run build
