name: React Vite PR Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Remove react-quill from package.json (temporary)
        run: |
          sudo apt-get install -y jq
          jq 'del(.dependencies["react-quill"])' package.json > temp.json && mv temp.json package.json
          rm -rf node_modules package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Install rollup from source (optional fix for native build)
        run: npm install rollup@latest --build-from-source

      - name: Build project
        run: npm run build
